//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Md5Checker.rc
//
#define IDC_MD5CHECKER                  100
#define IDS_APP_TITLE                   101
#define IDS_APP_DESC                    102
#define IDS_FILE_TYPE                   103
#define IDS_FILE_FILTER                 104
#define IDS_SHELL_CONTEXT_MENU          105
#define IDS_SCM_CHECK_NEW_ONLY          106
#define IDS_VERSION_URL                 107
#define IDS_DOWNLOAD_URL                108
#define IDS_HELP_URL                    109
#define IDS_NAME                        110
#define IDS_IN_FOLDER                   111
#define IDS_CURRENT_MD5                 112
#define IDS_SAVED_MD5                   113
#define IDS_SIZE                        114
#define IDS_DATE_MODIFIED               115
#define IDS_STATUS_BAR_UNSELECTED       116
#define IDS_STATUS_BAR_SELECTED         117
#define IDS_STATUS_BAR_ADDING           118
#define IDS_STATUS_BAR_CHECKING         119
#define IDS_OFN_FOLDER                  120
#define IDS_OPTIONS_CAPTION             121
#define IDS_DEFAULT_CODE_PAGE_NAME      122
#define IDS_NONE                        123
#define IDS_SAME                        124
#define IDS_DIFFERENT                   125
#define IDS_ABORT                       126
#define IDS_ABORT_ADDING                127
#define IDS_SAVING_FAILED               128
#define IDB_MAIN_TOOLBAR                128
#define IDS_CHECK_FOR_UPDATES           129
#define IDB_VIEW_TOOLBAR                129
#define IDS_CFU_ERROR                   130
#define IDC_HAND                        130
#define IDS_CFU_NA                      131
#define IDD_ABOUT                       131
#define IDS_CFU_AVAILABLE               132
#define IDD_PROPPAGE_ADD                132
#define IDD_PROPPAGE_SAVE               133
#define IDD_PROPPAGE_INTEGRATION        134
#define IDD_PROPPAGE_ADVANCED           135
#define IDD_ADD_OPTIONS_EMBEDDED        136
#define IDD_ADD_OPTIONS_STANDALONE      137
#define IDD_SAVE_OPTIONS_EMBEDDED       138
#define IDD_SAVE_OPTIONS_STANDALONE     139
#define IDD_COMPARE_MD5                 140
#define IDD_MD5_CALCULATOR              141
#define IDI_MD5CHECKER                  142
#define IDI_SMALL                       143
#define IDI_MD5CHECKER_DOC              144
#define IDR_CONTEXT_MENUS               145
#define IDC_HOMEPAGE_URL                1000
#define IDC_DOWNLOAD_URL                1001
#define IDC_AUTO_START                  1002
#define IDC_CHECK_NEW_ONLY              1003
#define IDC_INCLUDE                     1004
#define IDC_EXCLUDE                     1005
#define IDC_RECURSE                     1006
#define IDC_FOLDERNAME                  1007
#define IDC_SPECIFY_NAME                1008
#define IDC_SPECIFIED_NAME              1009
#define IDC_ID_SPACE_ASTERISK           1010
#define IDC_ID_SPACES                   1011
#define IDC_ID_VERTICAL_BAR             1012
#define IDC_LF_CR_LF                    1013
#define IDC_LF_LF                       1014
#define IDC_LF_CR                       1015
#define IDC_PD_BACKSLASH                1016
#define IDC_PD_SLASH                    1017
#define IDC_SAVE_TO_FULL_PATH           1018
#define IDC_ASSOCIATE                   1019
#define IDC_SHORTCUT                    1020
#define IDC_INTEGRATE                   1021
#define IDC_SEND_TO                     1022
#define IDC_LOW_PRIORITY                1023
#define IDC_STORE_LFU                   1024
#define IDC_CODE_PAGE                   1025
#define IDC_HIDE_ADD_OPTIONS            1026
#define IDC_HIDE_SAVE_OPTIONS           1027
#define IDC_DEFAULT                     1028
#define IDC_SAVE_SETTINGS               1029
#define IDC_FILE_PATH_1                 1030
#define IDC_MD5_1                       1031
#define IDC_COMPARE_RESULT              1032
#define IDC_FILE_PATH_2                 1033
#define IDC_MD5_2                       1034
#define IDC_PASTE_MD5                   1035
#define IDC_TEXT_INPUT                  1036
#define IDC_UNICODE                     1037
#define IDC_MD5_OUTPUT                  1038
#define IDC_CALCULATE_MD5               1039
#define IDC_COPY_MD5                    1040
#define ID_FILE_SAVE                    32771
#define ID_FILE_SAVE_EACH               32772
#define ID_FILE_SAVE_TO                 32773
#define ID_FILE_EXIT                    32774
#define ID_EDIT_ADD                     32775
#define ID_EDIT_REMOVE                  32776
#define ID_EDIT_CLEAR                   32777
#define ID_EDIT_START                   32778
#define ID_EDIT_STOP                    32779
#define ID_EDIT_COMPARE_MD5             32780
#define ID_EDIT_COPY                    32781
#define ID_EDIT_COPY_MD5                32782
#define ID_EDIT_COPY_PATHS              32783
#define ID_EDIT_DISCARDED               32784
#define ID_EDIT_SELECT_ALL              32785
#define ID_VIEW_ALL                     32786
#define ID_VIEW_NA                      32787
#define ID_VIEW_UNKNOWN                 32788
#define ID_VIEW_LOADED                  32789
#define ID_VIEW_NEW                     32790
#define ID_VIEW_FAILED                  32791
#define ID_VIEW_PASSED                  32792
#define ID_VIEW_LOCATE                  32793
#define ID_VIEW_PROPERTIES              32794
#define ID_TOOLS_SELFCHECK              32795
#define ID_TOOLS_MD5_CALCULATOR         32796
#define ID_TOOLS_OPTIONS                32797
#define ID_ONLINE_HELP                  32798
#define ID_HELP_CHECK_FOR_UPDATES       32799
#define ID_HELP_ABOUT                   32800
#define ID_ACCEL_EDIT_ADD               32801
#define ID_ACCEL_EDIT_CLEAR             32802
#define ID_ACCEL_EDIT_COMPARE_MD5       32803
#define ID_ACCEL_EDIT_COPY              32804
#define ID_ACCEL_EDIT_DISCARDED         32805
#define ID_ACCEL_EDIT_REMOVE            32806
#define ID_ACCEL_EDIT_SELECT_ALL        32807
#define ID_ACCEL_EDIT_START             32808
#define ID_ACCEL_EDIT_STOP              32809
#define ID_ACCEL_FILE_SAVE              32810
#define ID_ACCEL_FILE_SAVE_EACH         32811
#define ID_ACCEL_ONLINE_HELP            32812
#define ID_ACCEL_VIEW_LOCATE            32813
#define ID_ACCEL_VIEW_PROPERTIES        32814
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
